### PR TITLE
added read to * resource

### PR DESCRIPTION
**Pull request by ryandillinfelton**
We had a request from *the BU* to allow for permissions like `inventory:*:read` that were previously unsupported. This adds those new permissions to the config

### CODE REVIEW

**Review by tahmidefaz — APPROVED** [review]
LGTM :+1:

**Review by kruai — APPROVED** [review]
LGTM

**Comment by thearifismail** [comment]
LGTM

**Comment by ryandillinfelton** [comment]
@coderbydesign Is this good to merge now?

**Review by nicole-campbell12 — APPROVED** [review]

**Review by coderbydesign — APPROVED** [review]

**Pull request merged**
