### PR TITLE
NOTIF-361 Remove obsolete roles

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by bennetelli** [comment]
@theute is this as it should be?

**Comment by theute** [comment]
Reading the doc here: https://github.com/RedHatInsights/rbac-config#canned-roles it sounds like you need to bump the version number

**Comment by theute** [comment]
Maybe not, if you just rolledback

**Comment by bennetelli** [comment]
As far as I understand, this notifications:*:* covers the read:events:notifications in our notifications-backend project: https://github.com/RedHatInsights/notifications-backend/pull/756

**Comment by bennetelli** [comment]
Just talked to Keith Walsh. The version can stay as it is right now.

**Comment by josejulio** [comment]
Looks good to me!

**Pull request merged**
