### PR TITLE
Add Malware Detection application

### PR DESCRIPTION
**Pull request by dkuc**
Rbac config for the new insights application Malware Detection.  For version one there will be two roles/permissions 
* An admin role
* A read only role

### CODE REVIEW

**Review by coderbydesign — CHANGES_REQUESTED** [review]
@dkuc - To confirm, you're wanting the admin role/perm `malware-detection:*:*` to be given to everyone by default (this will _not_ be given to users who have already modified their default access group), with the ability to use `malware-detection:disable-signature:write` as a granular permission in custom role creation?

One thing worth updating would the the file name for the permission files. We should have it `malware-detection` since the permissions are dynamically generated based off the file name. Otherwise it would be `malware_detection:disasble-signature:write`.

**Comment by coderbydesign** [comment]
cc: @nicole-campbell12

**Comment by dkuc** [comment]
> One thing worth updating would the the file name for the permission files.

Done.

**Comment by dkuc** [comment]
Removed all platform default roles.

**Comment by dkuc** [comment]
Consolidated to an admin and reader role.

**Comment by dkuc** [comment]
Can you give a another review @coderbydesign ?

**Comment by dkuc** [comment]
@coderbydesign @nicole-campbell12  When do you think we can merge this in?

**Review by coderbydesign — APPROVED** [review]

**Pull request merged**
