### PR TITLE
Add approver role to admin for requests

### PR DESCRIPTION
**Pull request by hsong-rh**
https://projects.engineering.redhat.com/browse/SSP-1566

Grant admin with approve privilege when he is in an approver group

### CODE REVIEW

**Comment by gmcculloug** [comment]
cc @bzwei @mkanoor

**Comment by mkanoor** [comment]
👍

**Comment by bzwei** [comment]
Talking to @hsong-rh now. We may need more permissions for admin in order for their group to be added to workflow.

**Comment by hsong-rh** [comment]
@bzwei The permission is added.

**Comment by gmcculloug** [comment]
@coderbydesign Can you review and/or assign.  Thanks

**Pull request merged**
