### PR TITLE
[EVNT-697] Add notifications roles to Drift viewer and default admin groups

### PR DESCRIPTION
**Pull request by jpramos123**
Add notifications roles to Drift viewer and default admin groups

EVNT-697

### CODE REVIEW

**Review by sthirugn — APPROVED** [review]

**Comment by sthirugn** [comment]
@coderbydesign please get this change in stage, we missed a few permissions last time.

**Review by msager27 — APPROVED** [review]
lgtm

**Comment by jpramos123** [comment]
Hello @coderbydesign, can you take a look and merge this code so we can test it on stage?

Thanks

**Comment by coderbydesign** [comment]
@jpramos123 you'll need to bump the version number on the roles to pick up the changes, but then we can get this in!

**Comment by jpramos123** [comment]
> @jpramos123 you'll need to bump the version number on the roles to pick up the changes, but then we can get this in!

Done! Thanks for the heads up!

**Review by coderbydesign — APPROVED** [review]

**Pull request merged**
