### PR TITLE
Update platform default and promote provisioning roles/perms to prod

### PR DESCRIPTION
**Pull request by lzap**
This promotes provisioning perms/roles, which are in stage for quite some time now, to prod.

No changes were made, these are copies of stage files.

Is it possible to get to production by Aug 13th? Thanks.

### CODE REVIEW

**Comment by lpichler** [comment]
@lzap We are going to do it on Thursday.

**Comment by lzap** [comment]
I added one more one-liner: we want the Launch Viewer to be in the Default Access Group, so I added `platform_default` flag on stage and then in another commit I promote both files to prod.

**Comment by lzap** [comment]
@lpichler we are pushing to prod today, ready to flip the RBAC feature on in that environment when you say so. Thanks.

**Comment by lpichler** [comment]
> @lpichler we are pushing to prod today, ready to flip the RBAC feature on in that environment when you say so. Thanks.

@lzap we are going to do it in 2-3 hours approx. But in this case we will do stage first.

**Review by abaiken — APPROVED** [review]

**Comment by lpichler** [comment]
@lzap this is in prod, can you check it please ?

**Comment by lzap** [comment]
Well my account on prod does not have access to IdM. Need to figure out how to check that.

**Comment by lzap** [comment]
A colleague checked roles, they are there. Thank you.

**Pull request merged**
