### PR TITLE
Adding subscription's cloud access permissions for Stage ENV

### PR DESCRIPTION
**Pull request by sourabh-upadhyay**
- Adds **cloud_access**  permissions to **Subscriptions** to **Stage**

### CODE REVIEW

**Review by abaiken — COMMENTED** [review]
Hi! Can you separate this into two PRs (one with changes for stage and one with changes for prod)? We don't allow mixed environments in a single PR. TIA!

**Comment by sourabh-upadhyay** [comment]
> Hi! Can you separate this into two PRs (one with changes for stage and one with changes for prod)? We don't allow mixed environments in a single PR. TIA!

Sure, I will raise the separate MRs

**Comment by sourabh-upadhyay** [comment]
@abaiken can I have an eye on this?

**Review by abaiken — APPROVED** [review]
LGTM! Sorry for the delay!

**Pull request merged**
