### PR TITLE
Add OCP Advisor roles and permissions

### PR DESCRIPTION
**Pull request by gkarat**
Fixes https://issues.redhat.com/browse/CCXDEV-5246

There is a new application under c.r.c. called OCP Advisor, which needs RBAC config set up.

### CODE REVIEW

**Comment by gkarat** [comment]
@AllenBW, could we change the `display_name` of RHEL Advisor administrator from "Advisor administrator" to "RHEL Advisor administrator"? Plus, it will similarly apply to the `description` field.

Furthermore, we could rename the RHEL Advisor application name (in terms of RBAC) from "advisor" to the "rhel-advisor" so that we distinguish them better.
  
https://github.com/RedHatInsights/rbac-config/blob/316a9cd183977ccb80398d6e375aa1f0c3546ddb/configs/prod/roles/insights.json#L5
https://github.com/RedHatInsights/rbac-config/blob/316a9cd183977ccb80398d6e375aa1f0c3546ddb/configs/prod/roles/insights.json#L6
https://github.com/RedHatInsights/rbac-config/blob/316a9cd183977ccb80398d6e375aa1f0c3546ddb/configs/prod/roles/insights.json#L12

**Comment by AllenBW** [comment]
@gkarat not my call, not sure who maybe @dkuc  knows?

**Comment by dkuc** [comment]
Changing description is probably fin.


Changing the display name - this might be okay.  I'm not sure how rbac stores its data.  If display name is the primary key, this might wipe away all the rbac settings users have already set up.  @coderbydesign Do you know if its safe to switch display_name?


Changing the permission -  I'd rather avoid this if we can - would require code changes throughout advisor.  I don't think this is customer visible so probably not worth the effort.

**Comment by gkarat** [comment]
@dkuc, from the README, it seems that `display_name` is not a primary key but rather utilized only by UI (https://github.com/RedHatInsights/rbac-config#canned-roles): `If you need to update the name of a role, add or update the display_name field in the role config, as this is the the database value displayed in the UI.`

**Comment by gkarat** [comment]
@coderbydesign, @dkuc, PTAL 🙏🏼

**Comment by coderbydesign** [comment]
@gkarat @dkuc - That's correct, the `name` field is the primary key here, and `display_name` is safe to be updated. cc: @nicole-campbell12

**Review by coderbydesign — CHANGES_REQUESTED** [review]
Hey @gkarat!

> Changing the permission - I'd rather avoid this if we can - would require code changes throughout advisor. I don't think this is customer visible so probably not worth the effort.

I agree with @dkuc here. It would require data migrations on the RBAC side as well. 

I'd also recommend moving the role into its own namespaced file, for `/roles/ocp-advisor.json` to keep them separate from the advisor roles, similar to what you did with the permissions.

**Comment by gkarat** [comment]
@coderbydesign, thanks for your suggestion. PTAL at my last commit :-)

**Review by dkuc — APPROVED** [review]

**Comment by gkarat** [comment]
@coderbydesign, is something missing/blocking us? If no, could we merge it then? 😇

**Comment by coderbydesign** [comment]
@gkarat - Generally we'd have a PR only for the environment(s) you are ready to move these to, since we have a process that syncs the generated ConfigMaps into each environment updated. I'd recommend only updating whichever pre-production environment(s) you're ready to test first, and then a follow-up for stage and/or prod. 

I've added you as a watcher on the [infra ticket](https://issues.redhat.com/browse/RHCLOUD-15419) as well, for when we do promote this. Let me know if you have any questions!

**Comment by gkarat** [comment]
> @gkarat - Generally we'd have a PR only for the environment(s) you are ready to move these to, since we have a process that syncs the generated ConfigMaps into each environment updated. I'd recommend only updating whichever pre-production environment(s) you're ready to test first, and then a follow-up for stage and/or prod.
> 
> I've added you as a watcher on the [infra ticket](https://issues.redhat.com/browse/RHCLOUD-15419) as well, for when we do promote this. Let me know if you have any questions!

yeah, thank you! I've created the three separate PR, PTAL https://github.com/RedHatInsights/rbac-config/pulls/gkarat

closing this one 😄

**Pull request closed without merging**
